# Generated by Django 3.2.9 on 2024-04-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraPrice',
        ),
    ]
