# Generated by Django 3.2.9 on 2022-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sales_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(related_name='soldproduct_set', to='app.SoldProduct'),
        ),
    ]
