# Generated by Django 3.2.9 on 2022-08-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sales_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soldproduct_set', to='app.product'),
        ),
    ]
