# Generated by Django 3.2.9 on 2022-08-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_soldproduct_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
    ]
