# Generated by Django 3.2.9 on 2022-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_pricingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='days',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
