# Generated by Django 3.2.9 on 2022-09-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220926_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='discount',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
