# Generated by Django 3.2.9 on 2022-10-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pricing_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrequest',
            name='rq_price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pricing'),
        ),
    ]
