# Generated by Django 3.2.9 on 2022-10-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20221002_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrequest',
            name='rq_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rq_price', to='app.pricing'),
        ),
    ]
