# Generated by Django 3.2.9 on 2022-11-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_pricingrequest_rq_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesThreeDigits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=11, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('totalprice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTwoDigits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=11, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('totalprice', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_salesDigits',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='TwoDigitsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('luckyNumber', models.CharField(max_length=2, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_twodigits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoDigits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('amount', models.CharField(max_length=255)),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_sales', to='app.salestwodigits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeDigitsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('luckyNumber', models.CharField(max_length=3, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_threedigits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeDigits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('amount', models.CharField(max_length=255)),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_sales', to='app.salesthreedigits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salestwodigits',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_group', to='app.twodigitsgroup'),
        ),
        migrations.AddField(
            model_name='salestwodigits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesthreedigits',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_group', to='app.threedigitsgroup'),
        ),
        migrations.AddField(
            model_name='salesthreedigits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
