# Generated by Django 3.2.9 on 2022-11-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20221115_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='twodigitsgroup',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
