# Generated by Django 3.2.9 on 2022-11-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_twodigitsgroup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedigitsgroup',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twodigitsgroup',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
