# Generated by Django 3.2.9 on 2023-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20221126_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='deliveryCharges',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
