# Generated by Django 3.2.9 on 2023-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_sales_deliverycharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
