# Generated by Django 3.2.9 on 2023-10-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20231013_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='voucherNumber',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='receiptNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
