# Generated by Django 3.2.9 on 2023-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20231014_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='productid',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
