# Generated by Django 4.2.5 on 2023-11-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20231112_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='acc_type',
            field=models.CharField(default='Cashier', max_length=50, null=True),
        ),
    ]
