# Generated by Django 4.2.5 on 2023-11-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_device_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_payment',
            field=models.CharField(default=models.CharField(max_length=20), max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sales', models.ManyToManyField(related_name='customer_sales', to='app.sales')),
            ],
        ),
    ]
