# Generated by Django 4.2.5 on 2023-11-20 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_sales_customer_payment_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='customername',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customername',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_payment',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
