# Generated by Django 3.2.9 on 2023-11-23 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_customername_user_alter_customername_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_payment',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('products', models.ManyToManyField(related_name='suppliers', to='app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
