# Generated by Django 3.2.9 on 2023-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20231123_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_payment',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
