# Generated by Django 3.2.9 on 2023-12-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20231208_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='isDiscountAmount',
            field=models.BooleanField(default=False),
        ),
    ]
